name: Top issues
on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  ShowAndLabelTopIssues:
    name: Display and label top issues
    runs-on: ubuntu-latest
    steps:
      - name: Run top issues action
        uses: burghyburghy/composite_action@master
