name: Top issues","
on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  ShowAndLabelTopIssues:
    name: Display and label top issues
    runs-on: ubuntu-latest
    steps:
      - name: Run top issues action
        uses: burghyburghy/composite_action@main
      - name: print
        run: |
          cat /home/runner/work/_actions/burghyburghy/composite_action/main/README.md
